import './globals.css'
import {Sora} from 'next/font/google'
import Header from "@/components/header/Header";
import Modal from "@/components/modals/Modal";

const inter = Sora({subsets: ['latin']})

export const metadata = {
    title: 'Rental Platform',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">

        <body className={inter.className}>
        <Modal isOpen={true}/>
        <Header/>
        {children}</body>
        </html>
    )
}
