import './globals.css'
import {Sora} from 'next/font/google'
import Header from "@/app/components/header/Header";
import Modal from "@/app/components/modals/Modal";
import RegisterModal from "@/app/components/modals/RegisterModal";
import React from "react";
import LoginModal from "@/app/components/modals/LoginModal";

const inter = Sora({subsets: ['latin']})

export const metadata = {
    title: 'Rental Platform',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">

        <body className={inter.className}>

        <RegisterModal/>
        <LoginModal/>
        <Header/>
        {children}</body>
        </html>
    )
}
